package org.wso2.carbon.identity.oauth2.responsemode.provider;

import org.testng.Assert;
import org.testng.annotations.Test;
import org.testng.annotations.DataProvider;
import org.wso2.carbon.identity.oauth2.responsemode.provider.impl.FragmentResponseModeProvider;

public class FragmentResponseModeProviderTest {

    @DataProvider(name = "authorizationResponseDTOProvider")
    private Object[][] authorizationResponseDTOProvider() {

        return new Object[][] {
                // AuthorizationResponseDTO, expected redirect url
                {getAuthResponseDTO("https://www.google.com/redirects/redirect1", "code1"),
                        "https://www.google.com/redirects/redirect1#code=code1"},
                {getAuthResponseDTO("https://www.google.com/redirects/redirect2?param1=abc&param2=xyz",
                        "code2"), "https://www.google.com/redirects/redirect2?param1=abc&param2=xyz#code=code2"},

        };
    }

    @Test(dataProvider = "authorizationResponseDTOProvider", description = "Test whether the redirect url generated by " +
            "the ResponseModeProvider is correct.")
    public void testRedirectUrl(AuthorizationResponseDTO authorizationResponseDTO, String expectedRedirectUrl){

        String redirectUrl = new FragmentResponseModeProvider().getAuthResponseRedirectUrl(authorizationResponseDTO);

        Assert.assertTrue(redirectUrl.contains(authorizationResponseDTO.getRedirectUrl()), "Redirect url does not " +
                "contain the callback url provided in the AuthorizationResponseDTO.");
        Assert.assertTrue(redirectUrl.contains("#"), "Redirect url does not contain a fragment part.");
        Assert.assertTrue(redirectUrl.contains("code="), "Redirect url does not contain the authorization code.");
        Assert.assertEquals(redirectUrl, expectedRedirectUrl, "Redirect url is not as expected.");
    }

    /**
     * This method creates and returns dummy AuthorizationResponseDTO instance.
     * @return AuthorizationResponseDTO DTO
     */
    private AuthorizationResponseDTO getAuthResponseDTO(String redirectURI, String code){

        AuthorizationResponseDTO authorizationResponseDTO = new AuthorizationResponseDTO();
        authorizationResponseDTO.setRedirectUrl(redirectURI);

        authorizationResponseDTO.getSuccessResponseDTO().setAuthorizationCode(code);

        return authorizationResponseDTO;
    }
}
