CREATE TABLE IF NOT EXISTS AUTHORIZATION_DETAILS_TYPES(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TYPE VARCHAR(255) NOT NULL,
    CURSOR_KEY INTEGER DEFAULT 1,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR (255),
    JSON_SCHEMA CLOB NOT NULL,
    TENANT_ID INTEGER DEFAULT -1
);

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_USER_CONSENTED_AUTHORIZATION_DETAILS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CONSENT_ID VARCHAR(255) NOT NULL,
    TYPE_ID INTEGER NOT NULL,
    AUTHORIZATION_DETAILS CLOB NOT NULL,
    CONSENT BOOLEAN NOT NULL DEFAULT 1,
    TENANT_ID INTEGER NOT NULL DEFAULT -1
);

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_ACCESS_TOKEN_AUTHORIZATION_DETAILS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TYPE_ID INTEGER NOT NULL,
    AUTHORIZATION_DETAILS CLOB NOT NULL,
    TOKEN_ID VARCHAR (255),
    TENANT_ID INTEGER DEFAULT -1
);

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_AUTHZ_CODE_AUTHORIZATION_DETAILS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TYPE_ID CHAR(36) NOT NULL,
    AUTHORIZATION_DETAILS CLOB NOT NULL,
    CODE_ID VARCHAR (255),
    TENANT_ID INTEGER
);

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_AUTHORIZATION_CODE (
            CODE_ID VARCHAR (255),
            AUTHORIZATION_CODE VARCHAR (2048),
            CONSUMER_KEY_ID INTEGER,
            CALLBACK_URL VARCHAR (2048),
            SCOPE VARCHAR(2048),
            AUTHZ_USER VARCHAR (100),
            TENANT_ID INTEGER,
            USER_DOMAIN VARCHAR(50),
            TIME_CREATED TIMESTAMP,
            VALIDITY_PERIOD BIGINT,
            STATE VARCHAR (25) DEFAULT 'ACTIVE',
            TOKEN_ID VARCHAR(255),
            SUBJECT_IDENTIFIER VARCHAR(255),
            PKCE_CODE_CHALLENGE VARCHAR (255),
            PKCE_CODE_CHALLENGE_METHOD VARCHAR(128),
            AUTHORIZATION_CODE_HASH VARCHAR (512),
            IDP_ID INTEGER DEFAULT -1 NOT NULL
);

CREATE TABLE IF NOT EXISTS IDN_OAUTH2_USER_CONSENT (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(255) NOT NULL,
    APP_ID CHAR(36) NOT NULL,
    TENANT_ID INTEGER NOT NULL DEFAULT -1,
    CONSENT_ID VARCHAR(255) NOT NULL
);

INSERT INTO AUTHORIZATION_DETAILS_TYPES (TYPE, NAME, DESCRIPTION, JSON_SCHEMA, TENANT_ID)
VALUES ('test_type_v1', 'Test Type', 'Test Type V1', '{}', 1234);

INSERT INTO IDN_OAUTH2_AUTHORIZATION_CODE (CODE_ID, AUTHORIZATION_CODE, IDP_ID)
VALUES ('81197bc6-63f3-4c0f-90dd-1588076ab50f', 'b1b833f0-f605-4f5c-add6-38ea8ce1b969', 1);

INSERT INTO IDN_OAUTH2_USER_CONSENT (USER_ID, APP_ID, TENANT_ID, CONSENT_ID)
VALUES ('valid_user_id', 'valid_app_id', 1234, '52481ccd-0927-4d17-8cfc-5110fc4aa009');
