swagger: '2.0'
info:
  version: 1.1.0
  title: WSO2 Identity Server OAuth2 Dynamic Client Registration Endpoint
  description: >
    This document specifies an **OAuth2 Dynamic Client Registration Endpoint**
    for WSO2 **Identity Server** .


    It is written with [swagger 2](http://swagger.io/).
  contact:
    name: WSO2
    url: 'http://wso2.com/identity-and-access-management'
    email: architecture@wso2.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
schemes:
  - https
host: localhost
basePath: /api/identity/oauth2/dcr/v1.1
consumes:
  - application/json
produces:
  - application/json
paths:
  /register:
    post:
      description: |
        This API is used to create an OAuth2 application. If your want to create your application to use the implicit or authorization_code 
        grant types, you need to provide the redirect_uris field in your request. If you are using any other grant type, 
        such as password, you don't need to send the redirect_uri field in the request. Check the sample request given below.
      x-wso2-request: |
        curl -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H
        "Content-Type: application/json" -d '{
          "redirect_uris":[""],
          "client_name": "application_1",
          "grant_types": ["password"] }'
        "https://localhost:9443/api/identity/oauth2/dcr/v1.1/register"
      x-wso2-response: |
        "HTTP/1.1 201 Created"
        { "client_id": "s6BhdRkqt3",
        "client_secret":"ZJYCqe3GGRvdrudKyZS0XhGv_Z45DuKhCUk0gBR1vZk",
        "client_secret_expires_at": 1577858400,
        "redirect_uris":[""],
        "grant_types": ["password"],
        "client_name":"application_1" }
      description: |
        If you want to register an OAuth2 application with a specified client_id and secret, check the sample request given below.
      x-wso2-request: |
        curl -k -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H 
        "Content-Type: application/json" -d '{
         "client_name": "application_test",
         "grant_types": ["password"], 
         "ext_param_client_id":"provided_client_id0001", 
         "ext_param_client_secret":"provided_client_secret0001" }' 
        "https://localhost:9443/api/identity/oauth2/dcr/v1.1/register"
      x-wso2-response: |
        "HTTP/1.1 201 Created"
        {"client_name”:"application_test",
        "client_id":"provided_client_id0001",
        "client_secret":"provided_client_secret0001",
        "redirect_uris":[""],
        "grant_types": ["password"]}
      summary: |
        Registers an OAuth2 application
      operationId: registerApplication
      parameters:
        - name: registrationRequest
          in: body
          description: Application information to register.
          required: true
          schema:
            $ref: '#/definitions/registrationRequest'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/application'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        '409':
          description: Conflict
          schema:
            $ref: '#/definitions/error'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/error'
      tags:
        - OAuth2 DCR
  # Get application info by client name
    get:
      summary: |
        Get OAuth2 application information
      description: |
         This API is used to get/retrieve an OAuth2 application by client_name.
      x-wso2-request: |
        curl -X GET -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{}' "https://localhost:9443/api/identity/oauth2/dcr/v1.1/register?client_name=application_owner_application_1"
      x-wso2-response: |
        "HTTP/1.1 200 OK"
        { "client_id": "s6BhdRkqt3",
        "client_secret":"ZJYCqe3GGRvdrudKyZS0XhGv_Z45DuKhCUk0gBR1vZk",
        "client_secret_expires_at": 1577858400,
        "redirect_uris":["https://client.example.org/callback"],
        "client_name":"application_owner_application_1",
        "grant_types": ["password"]}
      operationId: getApplicationByName
      parameters:
        - name: client_name
          type: string
          in: path
          description: Unique identifier of the OAuth2 client application.
          required: true
      responses:
        '200':
          description: Successfully Retrieved
          schema:
            $ref: '#/definitions/application'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/error'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/error'
      tags:
        - OAuth2 DCR
# Endpoint to get application information
  /register/{client_id}:
    get:
      summary: |
        Get OAuth2 application information
      description: |
         This API is used to get/retrieve an OAuth2 application by client_id.
      x-wso2-request: |
        curl -X GET -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{}' "https://localhost:9443/api/identity/oauth2/dcr/v1.1/register/s6BhdRkqt3"
      x-wso2-response: |
        "HTTP/1.1 200 OK"
        { "client_id": "s6BhdRkqt3",
        "client_secret":"ZJYCqe3GGRvdrudKyZS0XhGv_Z45DuKhCUk0gBR1vZk",
        "client_secret_expires_at": 1577858400,
        "redirect_uris":["https://client.example.org/callback"],
        "grant_types": ["password"],
        "client_name":"application_owner_application_1" }
      operationId: getApplication
      parameters:
        - name: client_id
          type: string
          in: path
          description: Unique identifier of the OAuth2 client application.
          required: true
      responses:
        '200':
          description: Successfully Retrieved
          schema:
            $ref: '#/definitions/application'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/error'
      tags:
        - OAuth2 DCR
# Endpoint to delete OAuth2 application
    delete:
      summary: |
        Delete OAuth2 application
      description: |
         This API is used to delete an OAuth2 application by client_id.
      x-wso2-request: |
        curl -X DELETE -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d '{}' "https://localhost:9443/api/identity/oauth2/dcr/v1.1/register/s6BhdRkqt3"
      x-wso2-response: |
        "HTTP/1.1 204 No Content"
      operationId: deleteApplication
      parameters:
        - name: client_id
          type: string
          in: path
          description: Unique identifier of the OAuth2 client application.
          required: true
      responses:
        '204':
          description: Successfully deleted
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/error'
      tags:
        - OAuth2 DCR
# Endpoint uses to update OAuth2 application
    put:
      description: |
        This API is used to update an OAuth2 application.
      x-wso2-request: |
        curl -X PUT -H "Authorization: Basic YWRtaW46YWRtaW4=" -H
        "Content-Type: application/json" -d '{
          "redirect_uris":["https://client.example.org/callback"],
          "client_name": "application_1",
          "grant_types": ["password"] }'
        "https://localhost:9443/api/identity/oauth2/dcr/v1.1/register"
      x-wso2-response: |
        "HTTP/1.1 200 OK"
        { "client_id": "s6BhdRkqt3",
        "client_secret":"ZJYCqe3GGRvdrudKyZS0XhGv_Z45DuKhCUk0gBR1vZk",
        "client_secret_expires_at": 1577858400,
        "redirect_uris":["https://client.example.org/callback"],
        "grant_types": ["password"],
        "client_name":"application_owner_application_1" }
      summary: |
        Updates an OAuth2 application
      operationId: updateApplication
      parameters:
        - name: updateRequest
          in: body
          description: Application information to update.
          required: true
          schema:
            $ref: '#/definitions/updateRequest'
        - name: client_id
          type: string
          in: path
          description: Unique identifier for the OAuth2 client application.
          required: true
      responses:
        '200':
          description: Successfully updated
          schema:
            $ref: '#/definitions/application'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        '409':
          description: Conflict
          schema:
            $ref: '#/definitions/error'
        '500':
          description: Server Error
          schema:
            $ref: '#/definitions/error'
      tags:
        - OAuth2 DCR

definitions:
#-----------------------------------------------------
# The Registration Request Object
#-----------------------------------------------------
  registrationRequest:
    type: object
    required:
      - redirect_uris
      - client_name
    properties:
      redirect_uris:
        type: array
        items:
          type: string
      client_name:
        type: string
      client_id:
        type: string
      client_secret:
        type: string
      grant_types:
        type: array
        items:
          type: string
      application_type:
        type: string
      jwks_uri:
        type: string
      url:
        type: string
      ext_param_client_id:
        type: string
      ext_param_client_secret:
        type: string
      contacts:
        type: array
        items:
          type: string
      post_logout_redirect_uris:
        type: array
        items:
          type: string
      request_uris:
        type: array
        items:
          type: string
      response_types:
        type: array
        items:
          type: string
      ext_param_sp_template:
        type: string
      backchannel_logout_uri:
        type: string
      backchannel_logout_session_required:
        type: boolean
      ext_application_display_name:
        type: string
      token_type_extension:
        type: string
      ext_application_owner:
        type: string
      ext_application_token_lifetime:
        type: integer
        format: int64
      ext_user_token_lifetime:
        type: integer
        format: int64
      ext_refresh_token_lifetime:
        type: integer
        format: int64
      ext_id_token_lifetime:
        type: integer
        format: int64
      ext_pkce_mandatory:
        type: boolean
      ext_pkce_support_plain:
        type: boolean
      ext_public_client:
        type: boolean
#-----------------------------------------------------
# The Application Update Request Object
#-----------------------------------------------------
  updateRequest:
    type: object
    properties:
      redirect_uris:
        type: array
        items:
          type: string
      client_name:
        type: string
      client_id:
        type: string
      client_secret:
        type: string
      grant_types:
        type: array
        items:
          type: string
      backchannel_logout_uri:
        type: string
      backchannel_logout_session_required:
        type: boolean
      ext_application_display_name:
        type: string
      token_type_extension:
        type: string
      ext_application_owner:
        type: string
      ext_application_token_lifetime:
        type: integer
        format: int64
      ext_user_token_lifetime:
        type: integer
        format: int64
      ext_refresh_token_lifetime:
        type: integer
        format: int64
      ext_id_token_lifetime:
        type: integer
        format: int64
      ext_pkce_mandatory:
        type: boolean
      ext_pkce_support_plain:
        type: boolean
      ext_public_client:
        type: boolean
#-----------------------------------------------------
# The OAuth2 Application Object
#-----------------------------------------------------
  application:
    type: object
    properties:
      client_id:
        type: string
      client_secret:
        type: string
      client_secret_expires_at:
        type: integer
        format: int64
      redirect_uris:
        type: array
        items:
          type: string
      grant_types:
        type: array
        items:
          type: string
      client_name:
        type: string
      ext_application_owner:
        type: string
      ext_application_token_lifetime:
        type: integer
        format: int64
      ext_user_token_lifetime:
        type: integer
        format: int64
      ext_refresh_token_lifetime:
        type: integer
        format: int64
      ext_id_token_lifetime:
        type: integer
        format: int64
      ext_pkce_mandatory:
        type: boolean
      ext_pkce_support_plain:
        type: boolean
      ext_public_client:
        type: boolean
#-----------------------------------------------------
# The Error Response object
#-----------------------------------------------------
  error:
    type: object
    properties:
      error:
        type: string
      error_description:
        type: string
      traceId:
        type: string
